README.md
Document GitHub Pages Enable
Samples:
- https://cisco.github.io/cisco-mibs/
- https://cisco.github.io/cisco-mibs/supportlists/nexus9000/Nexus9000MIBSupportList.html
- https://cisco.github.io/cisco-mibs/supportlists/cat9500/CAT9500.html
- https://cisco.github.io/cisco-mibs/ucs-C-Series-mibs/ucs-C-supportlist.html
=> GitHub Pages Enable

v2/CISCO-URWB-MIB.my
publishing the CISCO-URWB-MIB MIB as requested by Yaojun Wei (yaojwei)
=> publish of CISCO-URWB-MIB

v2/CISCO-CABLE-PNM-MIB.my
Publishing MIB as per request from jianjhu
=> publishing CISCO-CABLE-PNM-MIB

v2/CISCO-ENTITY-VENDORTYPE-OID-MIB.my, v2/CISCO-PRODUCTS-MIB.my
=> CANA DEC 22 MIB publish

v2/AIRESPACE-WIRELESS-MIB.my, v2/CISCO-LWAPP-AP-MIB.my, v2/CISCO-LWAPP-DOT11-CLIENT-MIB.my, v2/CISCO-LWAPP-MOBILITY-EXT-MIB.my, v2/CISCO-LWAPP-REAP-MIB.my, v2/CISCO-LWAPP-ROGUE-MIB.my, v2/CISCO-LWAPP-WLAN-POLICY-MIB.my, v2/CISCO-LWAPP-WLAN-SECURITY-MIB.my
=> publishing wirless MIB

v2/CISCO-ENTITY-VENDORTYPE-OID-MIB.my, v2/CISCO-PRODUCTS-MIB.my, v2/OLD-CISCO-CHASSIS-MIB.my
=> CANA PUBLISH for Jan 2023

v2/CISCO-RTTMON-MIB.my, v2/CISCO-RTTMON-TC-MIB.my
publishing CISCO-RTTMON-MIB and CISCO-RTTMON-TC-MIB MIBs
=> publishing CISCO-RTTMON-MIB and CISCO-RTTMON-TC-MIB MIBs

v2/ASYNCOS-MAIL-MIB.txt, v2/IRONPORT-SMI.txt
Backing up copy of:
- https://www.cisco.com/web/ironport/tools/email/ASYNCOS-MAIL-MIB.txt
- https://www.cisco.com/web/ironport/tools/web/IRONPORT-SMI.txt
=> Add ASYNCOS and IRONPORT MIBS

v2/CISCO-ENTITY-VENDORTYPE-OID-MIB.my, v2/CISCO-PRODUCTS-MIB.my
=> CANA publish Mar 2023

v2/CISCO-AAA-SERVER-MIB.my
Publishing AAA SERVER MIB changes
=> publishing AAA MIB

v2/CISCO-URWB-MIB.my
=> publishing CISCO-URWB MIB

v2/CISCO-OPTICAL-OLC-MIB.my
=> publishing optical mib

v2/CISCO-IGNITION-MIB.my
publishing  CISCO-IGNITION-MIB MIB
=> publishing CISCO-IGNITION-MIB MIB

ucs-mibs/CISCO-UNIFIED-COMPUTING-MIB.my, ucs-mibs/CISCO-UNIFIED-COMPUTING-STORAGE-MIB.my, ucs-mibs/CISCO-UNIFIED-COMPUTING-TC-MIB.my
Fixed multiple invalid fields for UCS MIBS.
=> Fixed multiple invalid fields for UCS MIBS.

v2/CISCO-LWAPP-WLAN-POLICY-MIB.my
publishing CISCO-LWAPP-WLAN-POLICY-MIB MIB
=> publishing CISCO-LWAPP-WLAN-POLICY-MIB.my  MIB

v2/CISCO-SIP-UA-MIB.my
=> publishing CISCO-SIP-UA-MIB.my MIB

supportlists/cat9200/CAT9200.html, supportlists/cat9200_cx/CAT9200_CX.html
publishing cat9200 supportlist
=> publishing cat2900 html files

ucs-mibs/CISCO-UNIFIED-COMPUTING-TC-MIB.my
Adding readyForRemoval field for storage drives.
=> Adding readyForRemoval field for storage drives. Update CISCO-UNIFIED-COMPUTING-TC-MIB.my

v2/CISCO-SWITCH-ENGINE-MIB.my
Add Egress Netflow types to cseTcamUsageEntry
=> Add egress netflow to cseTcamResourceType

supportlists/fxos/fxos-supportlist.html, v2/CISCO-FIREPOWER-AP-TC-MIB.my
=> Add CISCO-FIREPOWER-AP-TC-MIB to list of FXOS mibs

v2/CISCO-SWITCH-ENGINE-MIB.my
Added new MIBS LblAH and LblAI
=> Add labelLblAH and labelLblAI MIBS

v2/CISCO-DLEP-MIB.my
=> publishing cisco dlep mib

v2/CISCO-FC-FE-MIB.my
publishing CISCO-FC-FE-MIB.my MIB
=> publishing CISCO-FC-FE-MIB.my

v2/AIRESPACE-WIRELESS-MIB.my
=> publishing AIRSPACE MIB

v2/CISCO-SDWAN-APP-ROUTE-MIB.my
We need to update CISCO-SDWAN-APP-ROUTE-MIB to reflect some OIDs that are not supported anymore
=> CSCwi77159 Updated CISCO-SDWAN-APP-ROUTE-MIB

v2/CISCO-ENTITY-VENDORTYPE-OID-MIB.my, v2/CISCO-PRODUCTS-MIB.my
=> CANA FEB publish

v2/CISCO-RF-MIB.my
=> publishing CISCO-RF-MIB.my

v2/AIRESPACE-WIRELESS-MIB.my, v2/CISCO-LWAPP-AP-MIB.my, v2/CISCO-LWAPP-DOT11-MIB.my, v2/CISCO-LWAPP-QOS-MIB.my, v2/CISCO-LWAPP-REAP-MIB.my, v2/CISCO-LWAPP-RF-MIB.my, v2/CISCO-LWAPP-TAGS-MIB.my, v2/CISCO-LWAPP-TC-MIB.my, v2/CISCO-LWAPP-WLAN-SECURITY-MIB.my
=> publishing WLC MIBs

ucs-mibs/CISCO-UNIFIED-COMPUTING-TC-MIB.my
Simple change just adding zen to two other areas.
=> Adding zen to more areas and fixing unit arch in the right area.

v2/CISCO-ENTITY-VENDORTYPE-OID-MIB.my, v2/CISCO-PRODUCTS-MIB.my
=> publishing MIB for MAY

ucs-C-Series-mibs/ucs-C-supportlist.html
Updated supported platforms.
Below new generation platforms are added in the supported list.
C220M6
C240M6
C225M6
C245M6
C220M7
C240M7
C225M8
C245M8
=> ucs-C-supportlist.html

v2/CISCO-ALARM-MIB.my
Update CISCO_ALARM_MIB.my file
=> updated CISCO-ALARM-MIB.my 

v2/CISCO-ST-TC.my
=> publish CISCO-TC MIB

v2/CISCO-RTTMON-MIB.my, v2/CISCO-RTTMON-TC-MIB.my
=> Nexus9000MIBSupportList 10.5(1)

v2/CISCO-LWAPP-DOT11-CLIENT-MIB.my
publishing CISCO-LWAPP-DOT11-CLIENT-MIB
=> publishing CISCO-LWAPP-DOT11-CLIENT-MIB

ucs-mibs/CISCO-UNIFIED-COMPUTING-TC-MIB.my
=> CSCwm52992: Need ddr5 support in CucsMemoryType

v2/CISCO-ENTITY-VENDORTYPE-OID-MIB.my, v2/CISCO-PRODUCTS-MIB.my
=> CANA for Dec 24

v2/CISCO-ENTITY-VENDORTYPE-OID-MIB.my, v2/CISCO-PRODUCTS-MIB.my
CANA - New OIDs for the month f Mar'25
=> CANA-March25

v2/CISCO-PROCESS-MIB.my
Publish XR changes CSCvi20206 to cisco-mibs
=> Publish CSCvi20206

v2/CISCO-ENTITY-VENDORTYPE-OID-MIB.my, v2/CISCO-PRODUCTS-MIB.my
=> CANA-Apr-25
